// Comprehensive list of genres available in Google Books API
// Based on Google Books API subject categories and common book classifications

export const GOOGLE_BOOKS_GENRES = [
  // Fiction Categories
  "Fiction",
  "Literary Fiction",
  "Historical Fiction",
  "Science Fiction",
  "Fantasy",
  "Mystery",
  "Thriller",
  "Suspense",
  "Crime",
  "Detective",
  "Horror",
  "Romance",
  "Contemporary Romance",
  "Historical Romance",
  "Paranormal Romance",
  "Adventure",
  "Action",
  "Western",
  "War",
  "Espionage",
  "Dystopian",
  "Utopian",
  "Alternate History",
  "Time Travel",
  "Steampunk",
  "Cyberpunk",
  "Urban Fantasy",
  "Epic Fantasy",
  "High Fantasy",
  "Dark Fantasy",
  "Magical Realism",
  "Gothic",
  "Psychological Thriller",
  "Legal Thriller",
  "Medical Thriller",
  "Techno-Thriller",
  "Cozy Mystery",
  "Hard-boiled",
  "Police Procedural",
  "True Crime",
  "Noir",
  "Satire",
  "Humor",
  "Comedy",
  "Parody",
  "Coming of Age",
  "Family Saga",
  "Generational Saga",
  "Chick Lit",
  "Women's Fiction",
  "LGBTQ+ Fiction",
  "Multicultural Fiction",
  "African American Fiction",
  "Asian American Fiction",
  "Latino Fiction",
  "Native American Fiction",
  "Jewish Fiction",
  "Christian Fiction",
  "Religious Fiction",
  "Inspirational Fiction",
  "Short Stories",
  "Novellas",
  "Anthologies",
  "Classic Literature",
  "Modern Classics",
  "World Literature",
  "Translated Fiction",

  // Non-Fiction Categories
  "Non-fiction",
  "Biography",
  "Autobiography",
  "Memoir",
  "History",
  "World History",
  "American History",
  "European History",
  "Ancient History",
  "Medieval History",
  "Modern History",
  "Military History",
  "Social History",
  "Cultural History",
  "Political History",
  "Economic History",
  "Art History",
  "Music History",
  "Science",
  "Physics",
  "Chemistry",
  "Biology",
  "Mathematics",
  "Astronomy",
  "Earth Sciences",
  "Environmental Science",
  "Medicine",
  "Health",
  "Psychology",
  "Sociology",
  "Anthropology",
  "Philosophy",
  "Religion",
  "Theology",
  "Spirituality",
  "Self-Help",
  "Personal Development",
  "Motivational",
  "Business",
  "Economics",
  "Finance",
  "Investing",
  "Entrepreneurship",
  "Management",
  "Leadership",
  "Marketing",
  "Politics",
  "Government",
  "Law",
  "Current Affairs",
  "Social Issues",
  "Education",
  "Teaching",
  "Parenting",
  "Family",
  "Relationships",
  "Marriage",
  "Dating",
  "Sexuality",
  "Gender Studies",
  "Women's Studies",
  "Men's Studies",
  "LGBTQ+ Studies",
  "Travel",
  "Travel Guides",
  "Adventure Travel",
  "Food",
  "Cooking",
  "Recipes",
  "Wine",
  "Nutrition",
  "Diet",
  "Fitness",
  "Exercise",
  "Sports",
  "Recreation",
  "Hobbies",
  "Crafts",
  "Art",
  "Photography",
  "Music",
  "Performing Arts",
  "Theater",
  "Dance",
  "Film",
  "Television",
  "Media Studies",
  "Communication",
  "Journalism",
  "Writing",
  "Language Arts",
  "Linguistics",
  "Literature Criticism",
  "Literary Theory",
  "Poetry",
  "Drama",
  "Essays",
  "Reference",
  "Dictionaries",
  "Encyclopedias",
  "Almanacs",
  "Atlases",
  "Study Guides",
  "Test Preparation",
  "Textbooks",
  "Academic",
  "Research",
  "Technology",
  "Computers",
  "Internet",
  "Programming",
  "Software",
  "Hardware",
  "Web Design",
  "Graphic Design",
  "Architecture",
  "Engineering",
  "Construction",
  "Transportation",
  "Automotive",
  "Aviation",
  "Maritime",
  "Agriculture",
  "Gardening",
  "Nature",
  "Animals",
  "Pets",
  "Wildlife",
  "Ecology",
  "Conservation",
  "Climate Change",
  "Sustainability",

  // Children's and Young Adult
  "Children's Books",
  "Picture Books",
  "Early Readers",
  "Chapter Books",
  "Middle Grade",
  "Young Adult",
  "Teen Fiction",
  "Teen Romance",
  "Teen Fantasy",
  "Teen Science Fiction",
  "Teen Mystery",
  "Teen Thriller",
  "Teen Horror",
  "Teen Contemporary",
  "Teen Historical Fiction",
  "Teen Dystopian",
  "Children's Fiction",
  "Children's Fantasy",
  "Children's Adventure",
  "Children's Mystery",
  "Children's Science Fiction",
  "Children's Historical Fiction",
  "Children's Non-fiction",
  "Educational",
  "Learning",
  "Activity Books",
  "Coloring Books",
  "Board Books",
  "Fairy Tales",
  "Folk Tales",
  "Mythology",
  "Legends",
  "Fables",
  "Nursery Rhymes",

  // Specialized Categories
  "Graphic Novels",
  "Comics",
  "Manga",
  "Superhero",
  "Slice of Life",
  "Action Comics",
  "Adventure Comics",
  "Fantasy Comics",
  "Science Fiction Comics",
  "Horror Comics",
  "Mystery Comics",
  "Romance Comics",
  "Historical Comics",
  "Biographical Comics",
  "Educational Comics",
  "Humor Comics",
  "Alternative Comics",
  "Independent Comics",
  "Webcomics",
  "Light Novels",
  "Visual Novels",
  "Game Guides",
  "Strategy Guides",
  "Gaming",
  "Role-Playing Games",
  "Board Games",
  "Card Games",
  "Puzzles",
  "Brain Teasers",
  "Trivia",
  "Crosswords",
  "Sudoku",
  "Word Games",

  // Regional and Cultural
  "African Literature",
  "Asian Literature",
  "European Literature",
  "Latin American Literature",
  "Middle Eastern Literature",
  "Australian Literature",
  "Canadian Literature",
  "British Literature",
  "American Literature",
  "Irish Literature",
  "Scottish Literature",
  "Welsh Literature",
  "French Literature",
  "German Literature",
  "Italian Literature",
  "Spanish Literature",
  "Russian Literature",
  "Chinese Literature",
  "Japanese Literature",
  "Korean Literature",
  "Indian Literature",
  "Arabic Literature",
  "Hebrew Literature",
  "Yiddish Literature",
  "Indigenous Literature",
  "Postcolonial Literature",
  "Diaspora Literature",
  "Immigrant Literature",
  "Exile Literature",

  // Time Periods
  "Ancient Literature",
  "Classical Literature",
  "Medieval Literature",
  "Renaissance Literature",
  "Enlightenment Literature",
  "Romantic Literature",
  "Victorian Literature",
  "Modernist Literature",
  "Postmodern Literature",
  "Contemporary Literature",
  "21st Century Literature",

  // Special Collections
  "Award Winners",
  "Bestsellers",
  "Book Club Picks",
  "Staff Picks",
  "New Releases",
  "Coming Soon",
  "Pre-orders",
  "Limited Editions",
  "Collector's Editions",
  "Rare Books",
  "Out of Print",
  "Vintage",
  "Antique",
  "First Editions",
  "Signed Copies",
  "Illustrated Books",
  "Large Print",
  "Audio Books",
  "E-books",
  "Digital",
  "Interactive",
  "Multimedia",

  // Academic Subjects
  "Textbook",
  "Academic Writing",
  "Research Methods",
  "Statistics",
  "Data Analysis",
  "Scientific Method",
  "Laboratory Manuals",
  "Course Materials",
  "Lecture Notes",
  "Study Materials",
  "Exam Preparation",
  "Graduate Studies",
  "Undergraduate",
  "Professional Development",
  "Continuing Education",
  "Certification",
  "Training Materials",
  "Workshops",
  "Seminars",
  "Conferences",

  // Miscellaneous
  "Journals",
  "Diaries",
  "Letters",
  "Correspondence",
  "Documents",
  "Archives",
  "Collections",
  "Compilations",
  "Selections",
  "Excerpts",
  "Adaptations",
  "Retellings",
  "Reimaginings",
  "Sequels",
  "Prequels",
  "Series",
  "Trilogies",
  "Sagas",
  "Cycles",
  "Omnibus",
  "Complete Works",
  "Collected Works",
  "Selected Works"
];

// Function to get all genres sorted alphabetically
export const getAllGenres = (): string[] => {
  return [...GOOGLE_BOOKS_GENRES].sort();
};

// Function to search genres by keyword
export const searchGenres = (keyword: string): string[] => {
  const searchTerm = keyword.toLowerCase().trim();
  if (!searchTerm) return getAllGenres();
  
  return GOOGLE_BOOKS_GENRES
    .filter(genre => genre.toLowerCase().includes(searchTerm))
    .sort();
};

// Function to get genres by category
export const getGenresByCategory = () => {
  return {
    fiction: GOOGLE_BOOKS_GENRES.filter(genre => 
      genre.includes('Fiction') || 
      ['Mystery', 'Thriller', 'Romance', 'Fantasy', 'Science Fiction', 'Horror', 'Adventure', 'Western'].some(cat => genre.includes(cat))
    ),
    nonFiction: GOOGLE_BOOKS_GENRES.filter(genre => 
      genre.includes('Non-fiction') || 
      ['Biography', 'History', 'Science', 'Business', 'Self-Help', 'Health', 'Travel', 'Cooking'].some(cat => genre.includes(cat))
    ),
    childrens: GOOGLE_BOOKS_GENRES.filter(genre => 
      genre.includes("Children's") || genre.includes('Young Adult') || genre.includes('Teen')
    ),
    academic: GOOGLE_BOOKS_GENRES.filter(genre => 
      ['Academic', 'Textbook', 'Education', 'Research', 'Study'].some(cat => genre.includes(cat))
    )
  };
};

